import 'package:prideldelivery/utils/constants.dart';

Map<String, String> defaultLanguageTranslatedValues = {
  "skip": "Skip",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "login": "Login",
  "welcome_back": "Hi, Welcome Back!",
  "please_enter_login_details":
      "Please enter your login details below to start using app.",
  "mobile_number": "Mobile Number",
  "we_will_send_verification_code_to":
      "We will send a password reset link to your registered email ID.",
  "dont_have_account": "Don't have an account?",
  "enter_valid_mobile_number": "Please enter valid mobile number",
  "password": "Password",
  "forgot_password": "Forgot Password?",
  "forgot_password_title": "Forgot Password",
  "get_password": "Get Password",
  "reset_password": "Reset password",
  "new_password": "New password",
  "confirm_new_password": "Confirm New Password",
  "change_password": "Change Password",
  "notification_pref": "Notifications Preference",
  "current_password": "Current Password",
  "enter_your_current_password": "Enter your current password",
  "enter_your_new_password": "Enter your new password",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "yes_logout": "Yes, Logout",
  "stay_logged_in": "Stay logged in",
  "are_you_sure_you_want_to_delete_account":
      "Are you sure you want to delete your account?",
  "yes_delete": "Yes, Delete",
  "keep_account": "Keep account",
  "notifications": "Notifications",
  "push_notifications": "Push Notifications",
  "promotional_emails": "Promotional Emails",
  "promotional_s_m_s": "Promotional SMS",
  "save_password": "Save Password",
  "delete_my_account": "Delete My Account Now",
  "backto_settings": "Back to Settings",
  "deleteAccntWarning1":
      "Please note that this action is irreversible and will permanently remove your account information.",
  "deleteAccntWarning2":
      "By deleting your account, you'll lose access to your order history and personalized settings. If you have any queries, don't hesitate to contact us.",
  "default_error_message": "Something went wrong.Please try again later!",
  "no_data_found": "No data found",
  "no": "No",
  "yes": "Yes",
  "terms_and_conditions": "Terms & Conditions",
  "privacy_policy": "Privacy Policy",
  "shipping_policy": "Shipping Policy",
  "return_policy": "Return and Refund Policy",
  "are_you_sure": "Are you sure?",
  "are_you_sure_to_exit_app": "Are you sure you want to exit the app?",
  "exit": "Exit",
  "submit": "Submit",
  "received": "Received",
  "awaiting": "Waiting",
  "processed": "Processed",
  "shipped": "Shipped",
  "delivered": "Delivered",
  "cancelled": "Cancelled",
  "returned": "Returned",
  "no_internet": "No Internet Connection. Please try again",
  "incorrect_o_t_p": "Incorrect otp",
  "retry": "Retry",
  "profile": "Profile",
  "internal_server_error_message":
      "Internal Server Error. Please try again later!",
  "data_not_available": "Data not available",
  "invalid_email_message": "Please enter valid email address",
  "empty_email_message": "Please enter email",
  "empty_value_message": "Please enter some text",
  "invalid_phone_message": "Please enter valid Mobile Number",
  "enter_name": "Please Enter Name",
  "enter_confirm_password": "Enter Confirmation Password",
  "confirm_password_do_not_match_with_new_password":
      "Confirmation Password not Matched",
  "app_language": "App Language",
  "empty_value_error_message": "Please enter some value",
  "incorrect_length_of_password_error":
      "The password must be at least 6 characters.",
  "app_under_maintenance":
      "Sorry for the inconvenience. This app is under maintenance.",
  "back_to_settings": "Back to Settings",
  "send": 'Send',
  "withdrawal_amount": 'Withdrawal Amount',
  "ifsc_code": "IFSC Code",
  "verification_error_message": "Verification failed. Please try again!",
  "invalid_email_error_message":
      "Email adddress is invalid. Pelase enter valid format",
  "invalid_name_error_message": "Name is invalid. Please enter valid format",
  "invalid_mobile_error_msg": "Please enter valid mobile number",
  "invalid_otp_message_error_msg": "OTP is incorrect",
  "password_mismatch_message":
      'Confirm Password do not match with new password',
  "please_login": "Please login to continue",
  "require_recent_login_error_message":
      'The user must relogin before this operation can be executed.\nThen you can initiate delete procedure.',
  "require_recent_login": 'Require Recent Login',
  "deactivated_error_message": 'You are deactivated. You can\'t login to app.',
  "home": "Home",
  "my_delivery": "My Delivery",
  "cash": "Cash",
  "user": "User",
  "change_language": "Change Language",
  "contact_us": "Contact us",
  "about_us": "About us",
  "terms_and_policy": "Terms and Policies",
  "rate_us": "Rate Us",
  "logout": "Logout",
  "delete_account": "Delete Account",
  "edit_profile": "Edit profile",
  "wallet": "Wallet",
  "cancel": "Cancel",
  "settings": "Settings",
  "support_and_info": "Support & Information",
  "more": "More",
  "my_profile": "My Profile",
  "order_details": "Order Details",
  "order_date_time": "Order Date/Time",
  "order_i_d": "Order ID",
  "payment_method": "Payment Method",
  "type": "Type",
  "status": "Status",
  "from_date": "From Date",
  "to_date": "To Date",
  "lbl_search": "Search",
  "search_all_orders": "Search all orders",
  "order_filter": "Order Filter",
  "clear_filters": "Clear Filters",
  "apply": "Apply",
  "simple": "Simple",
  "digital": "Digital",
  "order_status": "Order Status",
  "update": "Update",
  "shipping_details": "Shipping Details",
  "delivery_preference": "Delivery Preference",
  "price_details": "Price Details",
  "phone_number": "Phone Number",
  "delivery_instruction": "Delivery Instruction",
  "subtotal": "Subtotal",
  "tax": "Tax",
  "shipping_charges": "Shipping Charges",
  "wallet_balance": "Wallet Balance",
  "discount_amount": "Discount Amount",
  "promo_code_discount": "Promo Code Discount",
  "payable_total": "Payable Total",
  "total_amount": "Total Amount",
  "lbl_order_created": "Order created",
  "payment_mode": "Payment Mode",
  "return_request_pending": "Return Pending",
  "return_request_approved": "Return Approved",
  "return_request_decline": "Return Decline",
  "return_pickedup": "Return pickedup",
  "all": "All",
  "wallet_withdraw": "Wallet Withdraw",
  "withdraw": "Withdraw",
  "pending": "Pending",
  "approved": "Approved",
  "rejected": "Rejected",
  "current_balance": "Current Balance",
  "withdraw_money": "Withdraw Money",
  "wallet_transaction": "Wallet Transaction",
  "account_number": "Account Number",
  "name": "Name",
  "bank_details": "Bank Details",
  "success": "Success",
  "message": "Message",
  "date": "Date",
  "amount": "Amount",
  "collected": "Collected",
  "cash_collection": "Cash Collection",
  "rider_cash": "Rider Cash",
  "email": "Email",
  "address": "Address",
  "dl_front_image": "Driving Licence Front Image",
  "dl_back_image": "Driving Licence Back Image",
  "img_size_info": "(Recommended Size : 180 x 200 pixels)",
  "confirm_password": "Confirm Password",
  "upload_licence_warning": "Upload Driving Licence",
  "upload_profile_warning": "Upload Profile Image",
  "serviceable_zipcodes": "Serviceable Zipcodes",
  "lbl_try_again": "Try Again",
  "serviceable_cities": "Serviceable Cities",
  "bonus_type": "Bonus Type",
  "bonus_amount": "Bonus Amount",
  "bonus_percentage": "Bonus Percentage",
  "percentage_per_order_item": "Percentage Per Order Item",
  "fixed_amount_per_order_item": "Fixed Amount Per Order Item",
  "welcome": "Welcome",
  "new": "New",
  "earlier": "Earlier",
  "balance": "Balance",
  "total_balance": "Total Balance",
  "total_bonus": "Total Bonus",
  "total_orders": "Total Orders",
  "bonus": "Bonus",
  "recent_orders": "Recent Orders",
  "no_orders_assigned": "No orders assigned yet!",
  "no_orders_assigned_subtext":
      "Don't worry, new deliveries will show up here soon. Stay ready!",
  "select_status": "Select Status",
  "seller": "Seller",
  "click_to_open_file": "Click to open file",
  "direction": "Direction",
  "storage_permission_not_granted": "Storage permission not granted",
  "off_notification_warning":
      "Are you sure you want to turn off notifications from $appName?",
  "select_zones": "Select Zones",
  "please_enter_required_fields": "Please enter all required fields",
  "enter_otp": "Enter OTP",
  "tax_already_included": "Tax Already Included",
  "demo_mode_on": "Modifications are not allowed in demo app"
};
