name: Build Flutter APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          cache: true

      - name: Export Android SDK paths and accept licenses
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          find $ANDROID_SDK_ROOT/cmdline-tools -mindepth 1 -maxdepth 1 ! -name latest -exec cp -r {} $ANDROID_SDK_ROOT/cmdline-tools/latest/ \;
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | sdkmanager --licenses

      - name: Install Android SDK Build Tools 33.0.2
        run: |
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | sdkmanager "build-tools;33.0.2"
          yes | sdkmanager "platforms;android-35"
          yes | sdkmanager "platform-tools"

      - name: List installed Build Tools
        run: ls $ANDROID_SDK_ROOT/build-tools

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/delivery-file.jks

      - name: Create key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
